//! Raw FFI bindings to the CiFEr functional encryption library.
//!
//! This crate is auto-generated by bindgen from the CiFEr C headers.
//! It provides access to inner-product functional encryption primitives
//! used by the fingerprint system.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include the generated bindings (produced by build.rs).
// If CiFEr was not found during build, this file will not exist
// and the crate will compile as an empty stub.
#[cfg(feature = "cifer-linked")]
include!(concat!(env!("OUT_DIR"), "/cifer_bindings.rs"));
